function byId(id) {
    return document.getElementById(id);
}

export const refs = {
    btnAnalizar: byId('btnAnalizar'),
    chkAutoScan: byId('chkAutoScan'),
    btnLimpiar: byId('btnLimpiar'),
    btnConfig: byId('btnConfig'),
    btnExportLogs: byId('btnExportLogs'),
    btnSaveConfig: byId('btnSaveConfig'),
    configPanel: byId('configPanel'),
    consoleLog: byId('consoleLog'),
    chatBox: byId('chatBox'),
    chatInput: byId('chatInput'),
    btnSend: byId('btnSend'),
    searchInput: byId('searchInput'),
    searchBar: byId('searchBar'),
    backendStatus: byId('backendStatus'),
    btnRecord: byId('btnRecord'),
    recordingBar: byId('recordingBar'),
    recStepCount: byId('recStepCount'),
    journeysList: byId('journeysList'),
    playbackOverlay: byId('playbackOverlay'),
    playbackStepLabel: byId('playbackStepLabel'),
    btnStopPlayback: byId('btnStopPlayback'),
    apiKey: byId('apiKey'),
    modelId: byId('modelId'),
    tabLogs: byId('tabLogs'),
    tabChat: byId('tabChat'),
    tabJourneys: byId('tabJourneys'),
    tabTexts: byId('tabTexts'),
    viewLogs: byId('viewLogs'),
    viewChat: byId('viewChat'),
    viewJourneys: byId('viewJourneys'),
    viewTexts: byId('viewTexts'),
    btnAddTextStep: byId('btnAddTextStep'),
    btnAddKeyStep: byId('btnAddKeyStep'),
    btnAddWaitStep: byId('btnAddWaitStep'),
    textPickerPanel: byId('textPickerPanel'),
    textPickerList: byId('textPickerList'),
    btnCloseTextPicker: byId('btnCloseTextPicker'),
    keyPickerPanel: byId('keyPickerPanel'),
    keyPickerList: byId('keyPickerList'),
    btnCloseKeyPicker: byId('btnCloseKeyPicker'),
    btnNewText: byId('btnNewText'),
    btnCancelText: byId('btnCancelText'),
    btnSaveText: byId('btnSaveText'),
    textNameInput: byId('textNameInput'),
    textContentInput: byId('textContentInput'),
    textEditorPanel: byId('textEditorPanel'),
    textsList: byId('textsList')
};