import { initBackendStatus } from './backend-status.js';
import { initChat } from './chat.js';
import { initConfig } from './config.js';
import { initExportLogs } from './export-logs.js';
import { initExternalVariables } from './external-variables.js';
import { initJourneyPersistence } from './journeys/persistence.js';
import { initPlaybackControls } from './journeys/playback.js';
import { registerSidepanelMessageListeners } from './message-listeners.js';
import { initKeyPicker } from './recording/key-picker.js';
import { initRecordingControls } from './recording/controls.js';
import { initTextPicker } from './recording/text-picker.js';
import { initWaitStep } from './recording/wait-step.js';
import { initScan } from './scan.js';
import { initSearch } from './search.js';
import { initTabs } from './tabs.js';
import { initTextsPersistence } from './texts/persistence.js';
import { initTextsRender } from './texts/render.js';

initBackendStatus();
initConfig();
initTabs();
initScan();
initChat();
initSearch();
initRecordingControls();
initTextPicker();
initKeyPicker();
initWaitStep();
initJourneyPersistence();
initPlaybackControls();
initTextsPersistence();
initTextsRender();
initExternalVariables();
initExportLogs();
registerSidepanelMessageListeners();